### ISSUE TITLE
Does not work without profile, even if key/secret/etc are already provided in sampler parameters

### ISSUE THREAD

**Issue by jraoatlogic** [JoseLuisSR/awsmeter#11]
I set the correct aws_access_key_id, aws_secret_access_key, aws_region and sqs_queue_name in SQSProducerFifoQueue parameters, this should be enough to send a message to SQS, but I was unable to do so due to error:

```
software.amazon.awssdk.core.exception.SdkClientException: Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@1886ab0a: [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@47562565: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@1a67aa6: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@16549e69: Unable to contact EC2 metadata service.]
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98) ~[awsmeter-2.1.1.jar:?]
	at software.amazon.awssdk.regions.providers.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:70) ~[awsmeter-2.1.1.jar:?]
	at org.apache.jmeter.protocol.aws.AWSClient.getAWSRegion(AWSClient.java:35) ~[awsmeter-2.1.1.jar:?]

```

The reason seems to be that in `AWSClient.getAWSRegion()`, it's using `orElse()` which will execute the `getDefaultAwsRegionProviderChain`/`getRegion()` even if AWS region is already provided in `credentials`. It should be using `orElseGet()` instead.

The same problem exists in `AWSClient.getAWSAccessKeyId()` and `AWSClient.getAWSSecretAccessKey()` as well.

Once this is fixed, there is another issue that prevents me from using the sampler without a profile: if no session token is provided in credentials, `AWSClient.getAWSSessionToken()`'s `orElseGet()` will be run, it will throw exception if there's no profile. This should be changed so that if an exception is thrown, `getAWSSessionToken()` will return null, so that `AWSClientSDK2.getAwsCredentialsProvider()` will use basic credentials instead.

**Comment by jraoatlogic** [comment]
No problem, I have created PR: https://github.com/JoseLuisSR/awsmeter/pull/12
